package com.hasyame.marvelchampions.data

import android.content.Context
import androidx.test.core.app.ApplicationProvider
import com.hasyame.marvelchampions.data.marvelcdb.dto.ScenarioRulesFileDto
import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

/**
 * Guards `scenario_rules.json`, which is generated by
 * `tools/generate-scenario-rules.mjs` from prose on the scenario cards. A
 * MarvelCDB wording change would otherwise silently produce a file with fewer
 * scenarios or unresolved sets.
 */
@RunWith(RobolectricTestRunner::class)
class ScenarioRulesAssetTest {

    private val json = Json { ignoreUnknownKeys = true }

    private fun read(): ScenarioRulesFileDto {
        val context = ApplicationProvider.getApplicationContext<Context>()
        val text = context.assets.open("scenario_rules.json").bufferedReader().use { it.readText() }
        return json.decodeFromString(ScenarioRulesFileDto.serializer(), text)
    }

    @Test
    fun `covers every scenario marvelcdb publishes`() {
        // 53 as of 2026-08-06. It was 58: five villain sets bring no main
        // scheme and are not scenarios at all. A new one means the generator
        // needs rerunning.
        assertEquals(53, read().scenarios.size)
    }

    @Test
    fun `a villain set with no scenario of its own is not listed`() {
        // The four Wrecking Crew villains are played inside the Wrecking Crew
        // scenario, and the Marauders inside somebody else's. Listing them
        // offered "Bulldozer" as though you could sit down and play it.
        val codes = read().scenarios.map { it.code }

        listOf("bulldozer", "piledriver", "thunderball", "wrecker", "marauders").forEach {
            assertTrue("$it is not a scenario and must not be listed", it !in codes)
        }
        assertTrue("wrecking_crew is the scenario and must be", "wrecking_crew" in codes)
    }

    @Test
    fun `a scenario that uses no modular set is an answer, not a failure`() {
        // Wrecking Crew and Sinister Six name no modular sets. That used to be
        // flagged needsReview, so the app warned the player it could not read a
        // setup it had read correctly.
        val scenarios = read().scenarios
        listOf("wrecking_crew", "sinister_six").forEach { code ->
            val scenario = scenarios.single { it.code == code }
            assertEquals(0, scenario.modularCount)
            assertTrue("$code should not need review", scenario.needsReview != true)
        }
    }

    @Test
    fun `a set named with a typo on the card still resolves`() {
        // Batroc's own scenario card spells his brigade "Batrocs's Brigade".
        // Both of his mandatory sets have to survive that.
        val batroc = read().scenarios.single { it.code == "batroc" }

        assertEquals(
            listOf("a.i.m._science", "batrocs_brigade"),
            batroc.mandatoryModulars.sorted(),
        )
    }

    @Test
    fun `every scenario now parses`() {
        // Magog was the last entry needing review, on the grounds that it drew
        // from a pack the app could not enumerate. It could: "from the
        // MojoMania scenario pack" names a pack, and the generator resolves it
        // like any other reference.
        val review = read().scenarios.filter { it.needsReview == true }.map { it.code }
        assertEquals(emptyList<String>(), review)
    }

    @Test
    fun `a scenario that names its own pool records it`() {
        // All three MojoMania scenarios draw only from their own pack. Two of
        // them said so in a plain sentence and were silently recorded as
        // drawing from the whole collection, which is a setup the player cannot
        // put on the table.
        val scenarios = read().scenarios
        listOf("magog", "mojo", "spiral").forEach { code ->
            assertEquals(
                "$code draws only from the MojoMania pack",
                listOf("mojo"),
                scenarios.single { it.code == code }.modularPacks,
            )
        }
    }

    @Test
    fun `a scenario that scales with the table records the per-player set`() {
        // "Choose 1 modular set, plus 1[per_hero] additional modular sets."
        // Recorded as a flat 1, a four-player game got two sets instead of
        // five, and nothing said so.
        val scenarios = read().scenarios
        listOf("mojo", "thunderbolts").forEach { code ->
            val scenario = scenarios.single { it.code == code }
            assertEquals("$code adds a set per player", 1, scenario.modularCountPerHero)
            assertEquals("$code starts from one set", 1, scenario.modularCount)
        }
    }

    @Test
    fun `scenario codes are unique`() {
        val codes = read().scenarios.map { it.code }
        assertEquals(codes.size, codes.distinct().size)
    }

    @Test
    fun `mandatory modular sets all exist in the modular set list`() {
        val file = read()
        val known = file.modularSets.map { it.code }.toSet()
        file.scenarios.forEach { scenario ->
            scenario.mandatoryModulars.forEach { modular ->
                assertTrue(
                    "${scenario.code} requires unknown modular set $modular",
                    modular in known,
                )
            }
        }
    }

    @Test
    fun `a scenario never demands more mandatory sets than its total`() {
        read().scenarios.forEach { scenario ->
            assertTrue(
                "${scenario.code}: ${scenario.mandatoryModulars.size} mandatory " +
                    "but modularCount is ${scenario.modularCount}",
                scenario.mandatoryModulars.size <= scenario.modularCount,
            )
        }
    }

    @Test
    fun `modular counts are plausible`() {
        read().scenarios.forEach { scenario ->
            // Most scenarios use one or two. The Hood is the outlier at seven
            // ("Choose 7 modular encounter sets and set them aside"), so the
            // upper bound is a sanity check against a parse going haywire, not
            // a rule of the game.
            assertTrue(
                "${scenario.code} has modularCount ${scenario.modularCount}",
                scenario.modularCount in 0..8,
            )
        }
    }

    @Test
    fun `the scenarios in owned packs are present`() {
        val codes = read().scenarios.map { it.code }.toSet()
        // Sampled across the packs I own, including one campaign box each from
        // the two encodings MarvelCDB uses for main scheme cards.
        listOf("rhino", "klaw", "ultron", "risky_business", "brotherhood_of_badoon", "thanos")
            .forEach { assertTrue("$it missing from scenario_rules.json", it in codes) }
    }

    @Test
    fun `entries needing review stay few and are flagged, not guessed`() {
        val needsReview = read().scenarios.filter { it.needsReview }
        // 9 as generated on 2026-08-01, only one of which is in a pack I own.
        // A jump here means the parser broke against new wording.
        assertTrue(
            "unexpectedly many unparsed scenarios: ${needsReview.map { it.code }}",
            needsReview.size <= 12,
        )
    }
}
