# -*- coding: utf-8 -*-
"""Builds app/src/main/assets/rules_reference.json from MarvelCDB's rules page.

A keyword lookup that works at a table with no signal. The page is one long
document with a heading per term, so the terms are the headings and the body is
whatever sits between one heading and the next.

English only for now; the French column is left empty and can be filled in by
hand the way the set names were, since MarvelCDB does not publish a translated
rules page.

Usage:
  python tools/build_rules_reference.py
"""
import json
import io
import re
import urllib.request

SOURCE = "https://marvelcdb.com/rules"
OUTPUT = "app/src/main/assets/rules_reference.json"

# The page carries a bootstrap modal and a navigation bar that also use h2.
# Anything without a body is not a glossary entry.
NOT_TERMS = {"MODAL TITLE"}


def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": "Thwart/1.0"})
    with urllib.request.urlopen(request) as response:
        return response.read().decode("utf-8", errors="replace")


def strip_tags(html):
    # Scripts and styles go body and all. Stripping tags alone keeps what was
    # between them, which is how the last entry on the page ended up carrying
    # the site's Google Analytics snippet: the final <h2> takes everything after
    # it, and everything after it includes the footer scripts.
    text = re.sub(r"<(script|style)[^>]*>.*?</\1\s*>", " ", html, flags=re.I | re.S)
    # Paragraph and list boundaries become newlines before the tags go, or the
    # whole entry arrives as one run-on sentence.
    text = re.sub(r"<\s*/?\s*(p|br|li|div|tr)[^>]*>", "\n", text, flags=re.I)
    text = re.sub(r"<[^>]+>", "", text)
    text = (text.replace("&nbsp;", " ").replace("&amp;", "&")
                .replace("&lt;", "<").replace("&gt;", ">")
                .replace("&quot;", '"').replace("&#39;", "'"))
    lines = [" ".join(line.split()) for line in text.split("\n")]
    return "\n".join(line for line in lines if line).strip()


def content_only(html):
    """Everything before the page furniture.

    The last heading takes all the markup that follows it, and what follows it
    is the site footer and a hidden card modal. Without this the final entry
    ends in "Deck Quantity:" and a disclaimer about Fantasy Flight Games.
    """
    for marker in ('<div id="push"', "<footer"):
        cut = html.find(marker)
        if cut > 0:
            return html[:cut]
    return html


def main():
    html = content_only(fetch(SOURCE))

    # Split on headings, keeping the heading with the block that follows it.
    parts = re.split(r"<h2[^>]*>(.*?)</h2>", html, flags=re.S)
    entries = []
    # parts[0] is whatever came before the first heading.
    for index in range(1, len(parts) - 1, 2):
        term = strip_tags(parts[index])
        body = strip_tags(parts[index + 1])
        if not term or term.upper() in NOT_TERMS or not body:
            continue
        entries.append({"term": term, "en": body, "fr": None})

    document = {
        "_note": (
            "Generated by tools/build_rules_reference.py from " + SOURCE + ". The Rules "
            "Reference as MarvelCDB publishes it, so a keyword can be looked up at a "
            "table with no signal. French is null until somebody fills it in; there is "
            "no translated rules page to scrape."
        ),
        "source": SOURCE,
        "entries": entries,
    }

    with io.open(OUTPUT, "w", encoding="utf-8", newline="\n") as out:
        json.dump(document, out, ensure_ascii=False, indent=2)
        out.write("\n")

    longest = max(entries, key=lambda e: len(e["en"]))
    print("entries:", len(entries))
    print("first:", entries[0]["term"], "| last:", entries[-1]["term"])
    print("longest:", longest["term"], len(longest["en"]), "chars")


main()
